packages:
  - "apps/*"
  - "packages/*"
  - "create-zstack"

allowBuilds:
  esbuild: true
  workerd: true
  msgpackr-extract: false
  sharp: true
  "@sentry/cli": true

minimumReleaseAgeExclude:
  - pg-protocol@1.16.0
  - pg@8.23.0
  - evlog@2.25.0
